### ISSUE TITLE
copying pages generates a 500 error

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#1023]
Trying to copy a page on donate results in a 500 server error after making sure to use a unique slug and clicking the "copy" button.

STR:

- log into the admin
- pages => donate hompage => click on the page, not the edit icon
- pick the top page and try to copy it:

![image](https://user-images.githubusercontent.com/177243/85067840-314afd00-b166-11ea-8c53-3dd733b18991.png)

- ensure that there's a unique slug:

![image](https://user-images.githubusercontent.com/177243/85067897-49bb1780-b166-11ea-9ad9-058365e8ee37.png)

- press "copy this page": 

![image](https://user-images.githubusercontent.com/177243/85067917-53dd1600-b166-11ea-9695-d527abf8d605.png)

Heroku log details:

```bash
2020-06-18T20:15:38.415720+00:00 heroku[router]: at=info method=POST path="/admin/pages/41/copy/" host=donate.mozilla.org request_id=a4fba1fd-fed9-45d6-b2f0-bed467cdf5ca fwd="24.68.32.91" dyno=web.1 connect=1ms service=100ms status=500 bytes=1970 protocol=https
2020-06-18T20:15:38.416031+00:00 app[web.1]: Internal Server Error: /admin/pages/41/copy/
2020-06-18T20:15:38.416041+00:00 app[web.1]: Traceback (most recent call last):
2020-06-18T20:15:38.416041+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-06-18T20:15:38.416042+00:00 app[web.1]:     response = get_response(request)
2020-06-18T20:15:38.416045+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-06-18T20:15:38.416046+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-06-18T20:15:38.416047+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-06-18T20:15:38.416048+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-06-18T20:15:38.416048+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/contextlib.py", line 74, in inner
2020-06-18T20:15:38.416049+00:00 app[web.1]:     return func(*args, **kwds)
2020-06-18T20:15:38.416049+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
2020-06-18T20:15:38.416049+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)
2020-06-18T20:15:38.416050+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 105, in wrapper
2020-06-18T20:15:38.416050+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2020-06-18T20:15:38.416051+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/auth.py", line 167, in decorated_view
2020-06-18T20:15:38.416051+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2020-06-18T20:15:38.416051+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/auth.py", line 58, in wrapped_view_func
2020-06-18T20:15:38.416052+00:00 app[web.1]:     return view_func(request, *args, **kwargs)
2020-06-18T20:15:38.416052+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail/admin/views/pages.py", line 886, in copy
2020-06-18T20:15:38.416054+00:00 app[web.1]:     user=request.user,
2020-06-18T20:15:38.416054+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/wagtail_localize/models.py", line 387, in copy
2020-06-18T20:15:38.416054+00:00 app[web.1]:     original_process_child_object = kwargs.pop("process_child_object")
2020-06-18T20:15:38.416055+00:00 app[web.1]: KeyError: 'process_child_object'
2020-06-18T20:15:38.573375+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=donate.mozilla.org request_id=c451ae7c-3f39-4aa3-a41e-1ca389e4995c fwd="24.68.32.91" dyno=web.1 connect=1ms service=53ms status=404 bytes=11885 protocol=https
2020-06-18T20:15:38.829355+00:00 heroku[router]: at=info method=GET path="/es/thunderbird/?utm_source=thunderbird.net&utm_medium=referral&utm_content=post_download&tbdownload=true" host=donate.mozilla.org request_id=0a176b03-4572-46a0-8426-36e22d84fa79 fwd="181.56.87.104" dyno=web.1 connect=1ms service=37ms status=302 bytes=1568 protocol=https
```

**Comment by phildexter** [comment]
Doesn't look too clever. One for Kalob to help out with this week.

**Comment by TheoChevalier** [comment]
This can’t be reproduced anymore, closing this ticket
