### ISSUE TITLE
fix `review_app_admin` command

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#1621]
```
donate.users.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/app/donate/core/management/commands/review_app_admin.py", line 24, in handle
    password = Faker(
AttributeError: 'Faker' object has no attribute 'generate'
```

**Comment by Pomax** [comment]
This used the factory boy Faker, but without building a class that lets you call the code it was using. So, rather than the old format,

```
from factory import Faker

...

password = Faker('password', ...... ).generate({})
```

the "new" format is:

```
from factory.faker import faker
generator = faker.Faker()

...

password = generator.password(
  ......
)
```
