### ISSUE TITLE
Paypal transactions aren't getting to Salesforce

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#515]
One-time donations are the only ones working right now (see #514) and they show up in Braintree, but not Salesforce.

**Comment by alanmoo** [comment]
@solarissmoke If you get a chance today, can you confirm everything still looks right for Paypal->Basket?

**Comment by alanmoo** [comment]
Oh! It seems to be choking on `first_name`

```
2019-11-01T02:13:47.314277+00:00 app[worker.1]: 2019-11-01 02:13:47,313 [ERROR] KeyError: 'first_name'
2019-11-01T02:13:47.314282+00:00 app[worker.1]: Traceback (most recent call last):
2019-11-01T02:13:47.314288+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
2019-11-01T02:13:47.314294+00:00 app[worker.1]: rv = job.perform()
2019-11-01T02:13:47.314296+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rq/job.py", line 605, in perform
2019-11-01T02:13:47.314298+00:00 app[worker.1]: self._result = self._execute()
2019-11-01T02:13:47.314299+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
2019-11-01T02:13:47.314301+00:00 app[worker.1]: return self.func(*self.args, **self.kwargs)
2019-11-01T02:13:47.314303+00:00 app[worker.1]: File "/app/donate/payments/tasks.py", line 43, in send_transaction_to_basket
2019-11-01T02:13:47.314304+00:00 app[worker.1]: 'first_name': data['first_name'],
2019-11-01T02:13:47.314306+00:00 app[worker.1]: KeyError: 'first_name'
2019-11-01T02:13:47.314307+00:00 app[worker.1]: Traceback (most recent call last):
2019-11-01T02:13:47.314309+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
2019-11-01T02:13:47.314311+00:00 app[worker.1]: rv = job.perform()
2019-11-01T02:13:47.314312+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rq/job.py", line 605, in perform
2019-11-01T02:13:47.314314+00:00 app[worker.1]: self._result = self._execute()
2019-11-01T02:13:47.314315+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
2019-11-01T02:13:47.314317+00:00 app[worker.1]: return self.func(*self.args, **self.kwargs)
2019-11-01T02:13:47.314318+00:00 app[worker.1]: File "/app/donate/payments/tasks.py", line 43, in send_transaction_to_basket
2019-11-01T02:13:47.314320+00:00 app[worker.1]: 'first_name': data['first_name'],
2019-11-01T02:13:47.314321+00:00 app[worker.1]: KeyError: 'first_name'
```

**Comment by alanmoo** [comment]
I suspect I need to update [this function](https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/views.py#L362) to include references to first name. If so, I can add that in the morning.

Samir, any idea on why the tests didn't catch this?
