### ISSUE TITLE
Can't run donate-wagtail locally with DEBUG set to False

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#544]
If the `DEBUG` environment variable is set to False when running locally, HTTP requests to the site result in an internal server error.

```
backend_1             | Internal Server Error: /en-CA/
backend_1             | Traceback (most recent call last):
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
backend_1             |     response = get_response(request)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
backend_1             |     response = self.process_exception_by_middleware(e, request)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
backend_1             |     response = response.render()
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/response.py", line 106, in render
backend_1             |     self.content = self.rendered_content
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
backend_1             |     content = template.render(context, self._request)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
backend_1             |     return self.template.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 171, in render
backend_1             |     return self._render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
backend_1             |     return self.nodelist.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 937, in render
backend_1             |     bit = node.render_annotated(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
backend_1             |     return self.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
backend_1             |     return compiled_parent._render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
backend_1             |     return self.nodelist.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 937, in render
backend_1             |     bit = node.render_annotated(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
backend_1             |     return self.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
backend_1             |     return compiled_parent._render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
backend_1             |     return self.nodelist.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 937, in render
backend_1             |     bit = node.render_annotated(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
backend_1             |     return self.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
backend_1             |     result = block.nodelist.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 937, in render
backend_1             |     bit = node.render_annotated(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
backend_1             |     return self.render(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/templatetags/static.py", line 106, in render
backend_1             |     url = self.url(context)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/templatetags/static.py", line 103, in url
backend_1             |     return self.handle_simple(path)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/templatetags/static.py", line 118, in handle_simple
backend_1             |     return staticfiles_storage.url(path)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
backend_1             |     return self._url(self.stored_name, name, force)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
backend_1             |     hashed_name = hashed_name_func(*args)
backend_1             |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
backend_1             |     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
backend_1             | ValueError: Missing staticfiles manifest entry for '_js/main.compiled.js'
```

**Comment by solarissmoke** [comment]
@cadecairos if you want to run with `DEBUG=False` locally, you'll need to run the pre-deployment steps first (i.e., compile assets with `npm run build` and then collect them `manage.py collectstatic`).

**Comment by cadecairos** [comment]
for future reference: http://whitenoise.evans.io/en/stable/django.html#why-do-i-get-valueerror-missing-staticfiles-manifest-entry-for

**Comment by Pomax** [comment]
let's add that link to the docs and close this as out of date.
