### ISSUE TITLE
docker-new-env cannot finish due to missing merchant_id

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#587]
It will be good to make sure that `docker-new-env` checks that all necessary env vars are available before "really" running, with a notice to the user which expected env vars are missing, so they can make sure they have all the values set up to allow docker-new-env to finish its run.

It currently errors out citing:
```
Loading .env environment variables…
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/donate/payments/__init__.py", line 10, in <module>
    private_key=settings.BRAINTREE_PRIVATE_KEY
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/braintree/configuration.py", line 85, in __init__
    raise ConfigurationError("Missing merchant_id")
braintree.exceptions.configuration_error.ConfigurationError: Missing merchant_id
```

(alternatively, a fallback value in settings.py, or a dummy value in the default env?)

**Comment by patjouk** [comment]
Sorry about that :( You're probably the first one running the project from scratch in a long time, and I didn't do a great job at keeping the default up-to-date.
I'll check if we have proper defaults in #500. If not, I'll make the necessary changes.
